### PR TITLE
Pf (again)

### PR DESCRIPTION
**Pull request by tomster**
re-opening this after #57 - we still need to figure why restarting pf during jailhost configuration hangs - and i've also experienced hangs when creating new jails.

### CODE REVIEW

**Comment by fschulze** [comment]
Looks like ``/etc/rc.d/netif restart && /etc/rc.d/routing restart`` instead of ``/etc/netstart`` is the way to go. See http://www.cyberciti.biz/tips/freebsd-how-to-start-restart-stop-network-service.html
Will look at it later.

**Comment by tomster** [comment]
nah, that's not it, either. i've experimented some more today but w/o arriving at a solution...

it only affects the initial start of ``pf`` - once that hangs and i abort the configuration run and re-run it, it passes fine.

i've also tried reloading pf instead of restarting it but that doesn't help either.
since the error only manifests itself during the initial configuration run, debugging this is quite cumbersome, as each change requires a complete new bootstrap...

**Comment by tomster** [comment]
i'm still unsure about 9e28119, though.

what do you think?

**Comment by fschulze** [comment]
I thought you added support for multiple nat interfaces because you needed it. Did you add it just because you think it's needed? I certainly have a use case but am not sure it will work. Lets keep it in and fix it later if needed, it's harder to switch a variable name than it is to fix the implementation of it's use.

**Comment by fschulze** [comment]
Superseded by https://github.com/ployground/bsdploy/pull/64

**Pull request closed without merging**
