### PR TITLE
Enable encrypted ssh keys.

### PR DESCRIPTION
**Pull request by fschulze**
Not ready for merge yet, tests and changelog entry coming later.

### CODE REVIEW

**Comment by tomster** [comment]
btw, whatever happened to this? :)

**Comment by fschulze** [comment]
It works fine for me, but I didn't have time to write tests and docs yet.

**Comment by fschulze** [comment]
I finished this PR now.

**Comment by tomster** [comment]
tested locally by bootstrapping a fresh instance with encrypted host keys - worked like a charm!

**Pull request merged**
