### PR TITLE
Parametrise the jail interface, and allow other interfaces to be cloned ...

### PR DESCRIPTION
**Pull request by Infiniverse**
...on the jail host (vlans, etc).

This looks like a simple step in the right direction :).

### CODE REVIEW

**Comment by Infiniverse** [comment]
Hmm, how do I run the unit tests?

**Comment by fschulze** [comment]
Looks good, could you add a changelog entry? Otherwise I'll do it tomorrow.

**Comment by fschulze** [comment]
Run make in the checkout, then you should get a virtualenv with py.test 
etc. Or use tox.

**Comment by Infiniverse** [comment]
Hey fschulze, I've tweaked the change log as requested.

**Pull request merged**
