### PR TITLE
updated test_role with new/modified tasks.

### PR DESCRIPTION
**Pull request by mzs114**
Updated with a new, modified task from `jail_hosts/tasks/main.yml`

### CODE REVIEW

**Comment by fschulze** [comment]
Please update the exiting PR and don't make separate PRs for each fix. With separate PRs we don't see if the tests are fixed and the commit history isn't helpful at all.

**Comment by mzs114** [comment]
Sorry, I am new to sending in pull requests. Will remember this in the future.

**Comment by fschulze** [comment]
Just push your changes to the same git branch you created the initial PR with, then github will see the changes and update the PR.

**Comment by mzs114** [comment]
I have committed the required changes, the let me know if it worked.

**Comment by fschulze** [comment]
PR #81 looks good now, the test failures with older ansible versions seem to be unrelated, I saw them before.

**Pull request closed without merging**
